name: Deploy Databricks Bundle
on:
  push:
    branches:
      - main
      - uat
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Set deployment target
        id: set-target
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "target=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" == "uat" ]; then
            echo "target=uat" >> $GITHUB_OUTPUT
          else
            echo "target=dev" >> $GITHUB_OUTPUT
          fi
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main
      - name: Deploy bundle
        working-directory: ./project
        run: databricks bundle deploy --target ${{ steps.set-target.outputs.target }}
        env:
          DATABRICKS_HOST: https://dbc-344bfcd1-36e1.cloud.databricks.com
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
